# Конфигурация Leir4iks WireGuard VPN Plugin v3.0.0

vpn:
  # Порт для VPN сервера (по умолчанию WireGuard порт)
  port: 51820
  
  # Автоматический запуск VPN сервера при загрузке плагина
  auto-start: true
  
  # Внутренняя подсеть для VPN клиентов
  subnet: "10.0.0.0/24"
  
  # DNS серверы для клиентов
  dns:
    - "8.8.8.8"
    - "8.8.4.4"
    - "1.1.1.1"

# Настройки безопасности
security:
  # Максимальное количество одновременных подключений
  max-clients: 100
  
  # Тайм-аут соединения (секунды)
  connection-timeout: 300
  
  # Включить логирование трафика
  log-traffic: false

# Настройки производительности
performance:
  # Размер буфера для пакетов
  buffer-size: 65536
  
  # Количество рабочих потоков
  worker-threads: 4
