name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Create Gradle Wrapper if missing
      run: |
        if [ ! -f "./gradlew" ] || [ ! -f "./gradle/wrapper/gradle-wrapper.jar" ]; then
          echo "Creating Gradle Wrapper..."
          gradle wrapper --gradle-version 8.5 --distribution-type bin
          chmod +x gradlew
        fi
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: false
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Build JAR
      run: ./gradlew clean build jar
    
    # Загружаем артефакт только для main/master ветки
    - name: Upload JAR artifact
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: unzipper
        path: build/libs/wireguard-*.jar
        retention-days: 30
